apiVersion: v1
kind: Namespace
metadata:
  name: application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diplom-app
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diplom-app
  template:
    metadata:
      namespace: application
      labels:
        app: diplom-app
    spec:
      containers:
      - name: diplom-app
        image: hovard777/diplom:__VERSION__
        imagePullPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: diplom-app-service
  namespace: application
spec:
  selector:
    app: diplom-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      nodePort: 30082
  type: NodePort
