stages:
  - build
  - deploy

variables:
  CI_REGISTRY: docker.io
  CI_PROJECT_PATH: hovard777/diplom
  


build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  before_script:
    - |
      if [[ ! -z $DOCKER_HUB_WRITE_TOKEN ]]; then
        echo "Authenticating with DOCKER_HUB_WRITE_TOKEN"
        DOCKER_HUB_AUTH=`echo -n $REGISTRY_USER:$DOCKER_HUB_WRITE_TOKEN | base64 -w 0`
      fi
    - |
      mkdir -p /kaniko/.docker && \
      cat > /kaniko/.docker/config.json << EOT
      {
        "auths": {
          "https://index.docker.io/v1/": {
            "auth": "$DOCKER_HUB_AUTH"
          }
        }
      }
      EOT
  script:
    - cat /kaniko/.docker/config.json
    - >
      export TAG=$(if [[ "$CI_COMMIT_TAG"} ]]; then
                      echo ${CI_COMMIT_TAG};
                   else
                      echo ${CI_COMMIT_SHORT_SHA};
                   fi);
    - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile" --destination ${CI_PROJECT_PATH}:${TAG}


deploy:
  image: bitnami/kubectl:1.20
  stage: deploy
  before_script:
    - export KUBECONFIG=$KUBECONFIG

  script:
    - kubectl get pods -n application
    - sed -i "s,__VERSION__,${CI_COMMIT_TAG}," app.yaml
    - kubectl apply -f app.yaml
  only:
    - tags